In [12]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

## 1. Load both datasets

In [13]:
traffic = pd.read_csv("/content/Dataset_Uber Traffic.csv")
weather = pd.read_csv("/content/Bangalore Weather Data 2015-11-01 to 2017-06-30.csv")
events = pd.read_csv("/content/Bangalore_Special_Events_2015_2017.csv")

## 2. Fixing date formats

In [14]:
# Parse datetime
traffic["DateTime"] = pd.to_datetime(traffic["DateTime"], format="%d/%m/%y %H:%M", dayfirst=True)

# Create Date + Hour
traffic["Date"] = traffic["DateTime"].dt.date
traffic["Hour"] = traffic["DateTime"].dt.hour

# Sort
traffic = traffic.sort_values(by=["Junction", "DateTime"])

## 3. Clean and Prepare Important Weather Data

In [15]:
weather["Date"] = pd.to_datetime(weather["datetime"], format="%d/%m/%Y").dt.date

# Dropping unwanted columns
weather_clean = weather[['Date', 'temp', 'humidity', 'precip', 'windspeed', 'cloudcover', 'visibility', 'conditions']]

## 4. Merge Hourly Traffic Data wth Weather Data

In [16]:
merged = traffic.merge(weather_clean, on="Date", how="left")

In [17]:
# Checking the head and shape of the merged dataset
print(merged.head())
print(merged.shape)

             DateTime  Junction  Vehicles           ID        Date  Hour  \
0 2015-11-01 00:00:00         1        15  20151101001  2015-11-01     0
1 2015-11-01 01:00:00         1        13  20151101011  2015-11-01     1
2 2015-11-01 02:00:00         1        10  20151101021  2015-11-01     2
3 2015-11-01 03:00:00         1         7  20151101031  2015-11-01     3
4 2015-11-01 04:00:00         1         9  20151101041  2015-11-01     4

   temp  humidity  precip  windspeed  cloudcover  visibility  \
0  26.1      86.2   0.552       13.0        67.1         6.9
1  26.1      86.2   0.552       13.0        67.1         6.9
2  26.1      86.2   0.552       13.0        67.1         6.9
3  26.1      86.2   0.552       13.0        67.1         6.9
4  26.1      86.2   0.552       13.0        67.1         6.9

               conditions
0  Rain, Partially cloudy
1  Rain, Partially cloudy
2  Rain, Partially cloudy
3  Rain, Partially cloudy
4  Rain, Partially cloudy
(48120, 13)

## 5. Clean Events Data and Merge

In [18]:
events['Date'] = pd.to_datetime(events['date']).dt.date
events_clean = events.drop(columns=['date'])

In [19]:
# Merging events_clean with merged dataset
merged = merged.merge(events_clean, on = 'Date', how = 'left')

In [20]:
merged.head()

,DateTime,Junction,Vehicles,ID,Date,Hour,temp,humidity,precip,windspeed,cloudcover,visibility,conditions,event_name,category,impact_level
0,2015-11-01 00:00:00,1,15,20151101001,2015-11-01,0,26.1,86.2,0.552,13.0,67.1,6.9,"Rain, Partially cloudy",NaN,NaN,NaN
1,2015-11-01 01:00:00,1,13,20151101011,2015-11-01,1,26.1,86.2,0.552,13.0,67.1,6.9,"Rain, Partially cloudy",NaN,NaN,NaN
2,2015-11-01 02:00:00,1,10,20151101021,2015-11-01,2,26.1,86.2,0.552,13.0,67.1,6.9,"Rain, Partially cloudy",NaN,NaN,NaN
3,2015-11-01 03:00:00,1,7,20151101031,2015-11-01,3,26.1,86.2,0.552,13.0,67.1,6.9,"Rain, Partially cloudy",NaN,NaN,NaN
4,2015-11-01 04:00:00,1,9,20151101041,2015-11-01,4,26.1,86.2,0.552,13.0,67.1,6.9,"Rain, Partially cloudy",NaN,NaN,NaN

In [21]:
# Fill non-event days because null values are due to 'None' category
merged["event_name"] = merged["event_name"].fillna("No Event")
merged["category"] = merged["category"].fillna("No Category")
merged["impact_level"] = merged["impact_level"].fillna("No impact")

In [22]:
merged.head()

,DateTime,Junction,Vehicles,ID,Date,Hour,temp,humidity,precip,windspeed,cloudcover,visibility,conditions,event_name,category,impact_level
0,2015-11-01 00:00:00,1,15,20151101001,2015-11-01,0,26.1,86.2,0.552,13.0,67.1,6.9,"Rain, Partially cloudy",No Event,No Category,No impact
1,2015-11-01 01:00:00,1,13,20151101011,2015-11-01,1,26.1,86.2,0.552,13.0,67.1,6.9,"Rain, Partially cloudy",No Event,No Category,No impact
2,2015-11-01 02:00:00,1,10,20151101021,2015-11-01,2,26.1,86.2,0.552,13.0,67.1,6.9,"Rain, Partially cloudy",No Event,No Category,No impact
3,2015-11-01 03:00:00,1,7,20151101031,2015-11-01,3,26.1,86.2,0.552,13.0,67.1,6.9,"Rain, Partially cloudy",No Event,No Category,No impact
4,2015-11-01 04:00:00,1,9,20151101041,2015-11-01,4,26.1,86.2,0.552,13.0,67.1,6.9,"Rain, Partially cloudy",No Event,No Category,No impact

## 6. Saving the collaborated files into a csv file

Title- Traffic and Weather Merged Dataset_Atri Kar.csv

The following two lines of code have been commented as they are4 required only to download the merged dataset

In [23]:
merged.to_csv("Traffic and Weather Merged Dataset_Atri Kar.csv", index=False)

In [24]:
from google.colab import files
files.download("Traffic and Weather Merged Dataset_Atri Kar.csv")